window.env = {
  "TERM_PROGRAM": "vscode",
  "NODE": "/usr/local/bin/node",
  "INIT_CWD": "/Users/home/Documents/GitHub/chat_react",
  "SHELL": "/bin/bash",
  "TERM": "xterm-256color",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "TMPDIR": "/var/folders/jd/5hk9k4b97f74ndqlcdntb8mh0000gr/T/",
  "npm_config_global_prefix": "/usr/local",
  "Apple_PubSub_Socket_Render": "/private/tmp/com.apple.launchd.oxwM5lGZRC/Render",
  "TERM_PROGRAM_VERSION": "1.71.0",
  "MallocNanoZone": "0",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "COLOR": "1",
  "npm_config_noproxy": "",
  "npm_config_local_prefix": "/Users/home/Documents/GitHub/chat_react",
  "USER": "home",
  "npm_config_globalconfig": "/usr/local/etc/npmrc",
  "VRAY_FOR_MAYA2012_PLUGINS_x64": "/Applications/Autodesk/maya2012/Maya.app/Contents/vray/vrayplugins",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.lt5B6lB1rU/Listeners",
  "__CF_USER_TEXT_ENCODING": "0x1F8:0x0:0x0",
  "npm_execpath": "/usr/local/lib/node_modules/npm/bin/npm-cli.js",
  "PATH": "/Users/home/Documents/GitHub/chat_react/node_modules/.bin:/Users/home/Documents/GitHub/node_modules/.bin:/Users/home/Documents/node_modules/.bin:/Users/home/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin",
  "npm_package_json": "/Users/home/Documents/GitHub/chat_react/package.json",
  "_": "/Users/home/Documents/GitHub/chat_react/node_modules/.bin/react-dotenv",
  "npm_config_userconfig": "/Users/home/.npmrc",
  "npm_config_init_module": "/Users/home/.npm-init.js",
  "npm_command": "start",
  "PWD": "/Users/home/Documents/GitHub/chat_react",
  "npm_lifecycle_event": "start",
  "EDITOR": "vi",
  "npm_package_name": "react-homework-template",
  "LANG": "en_US.UTF-8",
  "XPC_FLAGS": "0x0",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "npm_config_node_gyp": "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "npm_package_version": "0.1.0",
  "XPC_SERVICE_NAME": "0",
  "VRAY_PATH": ":/Applications/ChaosGroup/V-Ray/Maya2012-x64/bin/x64/vc6:/Applications/ChaosGroup/V-Ray/Maya2012-x64/bin/x64/vc6",
  "HOME": "/Users/home",
  "VRAY_TOOLS_MAYA2012_x64": "/Applications/ChaosGroup/V-Ray/Maya2012-x64/bin",
  "SHLVL": "3",
  "VSCODE_GIT_ASKPASS_MAIN": "/private/var/folders/jd/5hk9k4b97f74ndqlcdntb8mh0000gr/T/AppTranslocation/DED14D5F-2958-46DD-805E-EE236B2AD3BF/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
  "VRAY_FOR_MAYA2012_PLUGINS_PowerPC": "/Applications/Autodesk/maya2012/Maya.app/Contents/vray/vrayplugins",
  "npm_config_cache": "/Users/home/.npm",
  "LOGNAME": "home",
  "npm_lifecycle_script": "react-dotenv && react-scripts start",
  "VRAY_FOR_MAYA2012_MAIN_x64": "/Applications/Autodesk/maya2012/Maya.app/Contents/vray",
  "VSCODE_GIT_IPC_HANDLE": "/var/folders/jd/5hk9k4b97f74ndqlcdntb8mh0000gr/T/vscode-git-845d4e67f7.sock",
  "npm_config_user_agent": "npm/8.11.0 node/v16.16.0 darwin x64 workspaces/false",
  "GIT_ASKPASS": "/private/var/folders/jd/5hk9k4b97f74ndqlcdntb8mh0000gr/T/AppTranslocation/DED14D5F-2958-46DD-805E-EE236B2AD3BF/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
  "VSCODE_GIT_ASKPASS_NODE": "/private/var/folders/jd/5hk9k4b97f74ndqlcdntb8mh0000gr/T/AppTranslocation/DED14D5F-2958-46DD-805E-EE236B2AD3BF/d/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper",
  "DISPLAY": "/private/tmp/com.apple.launchd.bQpcjDYJxy/org.macosforge.xquartz:0",
  "VRAY_FOR_MAYA2012_MAIN_PowerPC": "/Applications/Autodesk/maya2012/Maya.app/Contents/vray",
  "npm_node_execpath": "/usr/local/bin/node",
  "npm_config_prefix": "/usr/local",
  "COLORTERM": "truecolor",
  "API_KEY": "AIzaSyAA7ULFxIEBHmul3YBr6uYZaOk4z0cXefk",
  "AUTH_DOMAIN": "fir-db473.firebaseapp.com",
  "PROJECT_ID": "fir-db473",
  "STORAGE_BUCKET": "fir-db473.appspot.com",
  "MESSAGING_SENDER_ID": "354704188068",
  "APP_ID": "1:354704188068:web:e50687c6fe99a50a62bc31"
};